spring.datasource.url=jdbc:postgresql://localhost:5432/pos_db_spring
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=raffi-secret-key-for-learning-make-pos-api-with-springboot-java

server.port=8081